/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsiteRouteImport } from './routes/website'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MyBidsRouteImport } from './routes/my-bids'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AdminMobileRouteImport } from './routes/admin-mobile'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as DashboardSectionRouteImport } from './routes/dashboard.$section'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as AuctionIdRouteImport } from './routes/auction.$id'

const WebsiteRoute = WebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBidsRoute = MyBidsRouteImport.update({
  id: '/my-bids',
  path: '/my-bids',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMobileRoute = AdminMobileRouteImport.update({
  id: '/admin-mobile',
  path: '/admin-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mobile': typeof AdminMobileRoute
  '/auctions': typeof AuctionsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/website': typeof WebsiteRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/events/$id': typeof EventsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mobile': typeof AdminMobileRoute
  '/auctions': typeof AuctionsRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/website': typeof WebsiteRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/events/$id': typeof EventsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-mobile': typeof AdminMobileRoute
  '/auctions': typeof AuctionsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/my-bids': typeof MyBidsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/splash': typeof SplashRoute
  '/website': typeof WebsiteRoute
  '/auction/$id': typeof AuctionIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/events/$id': typeof EventsIdRoute
  '/product/$id': typeof ProductIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-mobile'
    | '/auctions'
    | '/dashboard'
    | '/events'
    | '/home'
    | '/live'
    | '/login'
    | '/my-bids'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/shop'
    | '/splash'
    | '/website'
    | '/auction/$id'
    | '/checkout/$id'
    | '/dashboard/$section'
    | '/events/$id'
    | '/product/$id'
    | '/dashboard/'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-mobile'
    | '/auctions'
    | '/home'
    | '/live'
    | '/login'
    | '/my-bids'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/shop'
    | '/splash'
    | '/website'
    | '/auction/$id'
    | '/checkout/$id'
    | '/dashboard/$section'
    | '/events/$id'
    | '/product/$id'
    | '/dashboard'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-mobile'
    | '/auctions'
    | '/dashboard'
    | '/events'
    | '/home'
    | '/live'
    | '/login'
    | '/my-bids'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/shop'
    | '/splash'
    | '/website'
    | '/auction/$id'
    | '/checkout/$id'
    | '/dashboard/$section'
    | '/events/$id'
    | '/product/$id'
    | '/dashboard/'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminMobileRoute: typeof AdminMobileRoute
  AuctionsRoute: typeof AuctionsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MyBidsRoute: typeof MyBidsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  SplashRoute: typeof SplashRoute
  WebsiteRoute: typeof WebsiteRoute
  AuctionIdRoute: typeof AuctionIdRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/website': {
      id: '/website'
      path: '/website'
      fullPath: '/website'
      preLoaderRoute: typeof WebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bids': {
      id: '/my-bids'
      path: '/my-bids'
      fullPath: '/my-bids'
      preLoaderRoute: typeof MyBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-mobile': {
      id: '/admin-mobile'
      path: '/admin-mobile'
      fullPath: '/admin-mobile'
      preLoaderRoute: typeof AdminMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminMobileRoute: AdminMobileRoute,
  AuctionsRoute: AuctionsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MyBidsRoute: MyBidsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  SplashRoute: SplashRoute,
  WebsiteRoute: WebsiteRoute,
  AuctionIdRoute: AuctionIdRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
